# Generated by Django 4.0.4 on 2022-07-08 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(default='', max_length=150)),
                ('Doctor', models.CharField(choices=[('Not Selected', 'Not Selected'), ('Dr One', 'Dr. Raj Kumar (Psychiatrist)'), ('Dr Two', 'Dr. Shiva (Radiologist)'), ('Dr Three', 'Dr. Ravi (Nerologist)')], default='Not Selected', max_length=150)),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
